config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'

  get 'pages/about'

  controller :sessions do
	get 'login' => :new
	post 'login' => :create
	get 'logout' => :destroy
	delete 'logout' => :destroy
  end
  
  resources :items do
  put :purchase
  end
  
  resources :items do
  put :rate1
  end
  
  resources :items do
  put :rate2
  end
  
  resources :items do
  put :rate3
  end
  
  resources :items do
  put :rate4
  end
  
  resources :items do
  put :rate5
  end

  
  get 'pages/signedUp'
  
  get 'pages/myaccount'
  
  get 'pages/myitems'
  
  get 'pages/mypurchases'
  
  get 'pages/solditems'
  
  get 'search',	:to=>'items#search'
  
  get 'purchase', :to=>'items#purchase'
  
  get 'rate1', :to=>'ratings#rate1'
  
  get 'rate2', :to=>'ratings#rate2'
  
  get 'rate3', :to=>'ratings#rate3'
  
  get 'rate4', :to=>'ratings#rate4'
  
  get 'rate5', :to=>'ratings#rate5'

  resources :users
  resources :ratings
  resources :categories
  resources :items

   root 'pages#home'

end

app/models/rating.rb
class Rating < ActiveRecord::Base
	belongs_to :item
	validates :score, presence: true #Not null	
	validates :item_id, presence: true #Not null	
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]
  before_action :authorise, only: [:new, :create, :edit, :update, :destroy]

  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
  end
  

	


  # POST /ratings
  # POST /ratings.json
  def create
    @rating = Rating.new(rating_params)

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @rating, notice: 'Rating was successfully created.' }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @rating, notice: 'Rating was successfully updated.' }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating.destroy
    respond_to do |format|
      format.html { redirect_to ratings_url, notice: 'Rating was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:score, :item_id)
    end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score, in: 1..5 %>
  </div>
    <div class="field">
    <%= f.label :item %><br>
    <%= f.collection_select :item_id, Item.all, :id, :title, value: %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings/_search.html.erb
<%= form_tag(search_path, method: :get) do %>
<%= text_field_tag(:query, params[:query]) %>
<%= submit_tag "Search for items" %>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
<h3>Ratings</h3>
  <table class="table">
    <thead>
      <tr>
        <th>Item</th>
		<th>Image</th>
		<th>Rating</th>
      </tr>
    </thead>
    <tbody>
     <% @ratings.each do |rating| %>
      <tr>
	    <td><%= rating.item.title %></td>
		<td><%= image_tag(rating.item.image, :size => "100x50") %></td>
        <td><%= rating.score  %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  
<%= link_to 'Back', root_path %> |
<%= link_to 'New Rating', new_rating_path %>
</div>

</body>
</html>

app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= render 'form' %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Score:</strong>
  <%= @rating.score %>
</p>

<p>
  <strong>Item:</strong>
  <%= @rating.item_id %>
</p>

<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>