config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'

  get 'pages/about'

  controller :sessions do
	get 'login' => :new
	post 'login' => :create
	get 'logout' => :destroy
	delete 'logout' => :destroy
  end
  
  resources :items do
  put :purchase
  end
  
  resources :items do
  put :rate1
  end
  
  resources :items do
  put :rate2
  end
  
  resources :items do
  put :rate3
  end
  
  resources :items do
  put :rate4
  end
  
  resources :items do
  put :rate5
  end

  
  get 'pages/signedUp'
  
  get 'pages/myaccount'
  
  get 'pages/myitems'
  
  get 'pages/mypurchases'
  
  get 'pages/solditems'
  
  get 'search',	:to=>'items#search'
  
  get 'purchase', :to=>'items#purchase'
  
  get 'rate1', :to=>'ratings#rate1'
  
  get 'rate2', :to=>'ratings#rate2'
  
  get 'rate3', :to=>'ratings#rate3'
  
  get 'rate4', :to=>'ratings#rate4'
  
  get 'rate5', :to=>'ratings#rate5'

  resources :users
  resources :ratings
  resources :categories
  resources :items

   root 'pages#home'

end

app/views/pages/_search.html.erb
<%= form_tag(search_path, method: :get) do %>
<%= text_field_tag(:query, params[:query]) %>
<%= submit_tag "Search for items" %>
<% end %>

app/views/pages/about.html.erb
<form>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-group">
    <label for="exampleInputFile">File input</label>
    <input type="file" id="exampleInputFile">
    <p class="help-block">Example block-level help text here.</p>
  </div>
  <div class="checkbox">
    <label>
      <input type="checkbox"> Check me out
    </label>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>
</form>

app/views/pages/home.html.erb
<h1>Dion Ho</h1>
	<h1><a href="https://github.com/dionho43/webdev1">Link to my Github</a></h1>
</form>

app/views/pages/myaccount.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <% if !signed_in? %>
		<h2>Welcome</h2>
		<h4>You need to be logged in to view your account<h4>
			<li><%=link_to "Register", new_user_path %></li>
			<li><%=link_to "Sign In", login_path %></li>
			
		<% else %>
			<h2>     Welcome <%= @current_user.username %></h2>
			<table class="table">
				<thead>
					<tr>
        <th>Username</th>
		<th>Address</th>
		<th>Phonenumber</th>
		<th>Email</th>
      </tr>
    </thead>
    <tbody>
      <tr>
			<td><%= @current_user.username %></td>
			<td><%= @current_user.address %></td>
			<td><%= @current_user.phoneNumber %></td>
			<td><%= @current_user.email %></td>
      </tr>
    </tbody>
  </table>

  
			<li><%=link_to "View my active items", pages_myitems_path%></li>
			<li><%=link_to "View my sold items", pages_solditems_path%></li>
			<li><%=link_to "View my purchases", pages_mypurchases_path%></li>
            <li><%=link_to "Edit Account", edit_user_path(@current_user)%></li>
			  <strong>Map:</strong>
  <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@current_user.latitude}%2C#{@current_user.longitude}" %>
	<% end %>
</div>

</body>
</html>

app/views/pages/myitems.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <% if !signed_in? %>
		<h1>Welcome</h1>
		<h4>You need to be logged in to view your items<h4>
			<li><%=link_to "Register", new_user_path %></li>
			<li><%=link_to "Sign In", login_path %></li>
			
		<% else %>
	<h2>     Items listed by user : <%= @current_user.username %></h1>
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
		<th>Image</th>
		<th>Price</th>
		<th>Location</th>
		<th>Time Left</th>
      </tr>
    </thead>
    <tbody>
     <% @current_user.items.each do |anything| %>
	 <% if anything.sold == false %>
      <tr>
        <td><%= anything.title  %></td>
        <td><%= image_tag(anything.attachment, :size => "100x50") %></td>
        <td><%= euro(anything.price) %></td>
        <td><%= anything.location %></td>
		<td><%= (30 - (Time.now - anything.created_at) / 24.hours).to_i %> Days</td>
		<td><%= link_to 'Edit', edit_item_path(anything) %></td>

      </tr>
    <% end %>
	<% end %>

    </tbody>
  </table>
  
	<li><%= link_to 'Back', pages_myaccount_path %></li>
	<% end %>
</div>

</body>
</html>

app/views/pages/mypurchases.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <% if !signed_in? %>
		<h1>Welcome</h1>
		<h4>You need to be logged in to view your purchases<h4>
			<li><%=link_to "Register", new_user_path %></li>
			<li><%=link_to "Sign In", login_path %></li>
			
		<% else %>
	<h2>     Purchases made by user : <%= @current_user.username %></h1>
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
		<th>Image</th>
		<th>Price</th>
		<th>Location</th>
		<th>Time Left</th>
		<th>Rating</th>
		<th></th>
		<th></th>
		<th></th>
		<th></th>
      </tr>
    </thead>
    <tbody>
     <% Item.all.each do |anything| %>
	 <% if anything.buyer == @current_user.username %>
      <tr>
        <td><%= anything.title  %></td>
        <td><%= image_tag(anything.attachment, :size => "100x50") %></td>
        <td><%= euro(anything.price) %></td>
        <td><%= anything.location %></td>
		<% if anything.sold == true %>
		<td> Sold : <%= anything.buyer %></td>
		<% else %>
		<td><%= (30 - (Time.now - anything.created_at) / 24.hours).to_i %> Days</td>
		<% end %>
		<% unless anything.ratings.any? %>
		<td>Leave a Rating</td>
		<td><%= link_to '1', item_rate1_path(anything.id), method: :put %></td>
		<td><%= link_to '2', item_rate2_path(anything.id), method: :put %></td>
		<td><%= link_to '3', item_rate3_path(anything.id), method: :put %></td>
		<td><%= link_to '4', item_rate4_path(anything.id), method: :put %></td>
		<td><%= link_to '5', item_rate5_path(anything.id), method: :put %></td>
		<% end %>
		<% if anything.ratings.any? %>
		<td>You Rated this Item : </td>
		<td><%= anything.ratings.first.score %></td>
		<% end %>
		

      </tr>
	  <% end %>
    <% end %>
    </tbody>
  </table>
	<li><%= link_to 'Back', pages_myaccount_path %></li>
	<% end %>
</div>

</body>
</html>

app/views/pages/solditems.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <% if !signed_in? %>
		<h1>Welcome</h1>
		<h4>You need to be logged in to view your items<h4>
			<li><%=link_to "Register", new_user_path %></li>
			<li><%=link_to "Sign In", login_path %></li>
			
		<% else %>
	<h2>     Items listed by user : <%= @current_user.username %></h1>
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
		<th>Image</th>
		<th>Price</th>
		<th>Location</th>
		<th>Buyer</th>
		<th>Rating</th>
      </tr>
    </thead>
    <tbody>
     <% @current_user.items.each do |anything| %>
	 <% if anything.sold == true %>
      <tr>
        <td><%= anything.title  %></td>
        <td><%= image_tag(anything.attachment, :size => "100x50") %></td>
        <td><%= euro(anything.price) %></td>
        <td><%= anything.location %></td>
		<td><%= anything.buyer %></td>
		<% unless !anything.ratings.any? %>
		<td><%= anything.ratings.first.score %></td>
		<% end %>

		<% if admin? %>
		<td><%= link_to 'Edit', edit_item_path(anything) %></td>
		<% end %>
      </tr>
    <% end %>
	<% end %>
    </tbody>
  </table>
  

	<li><%= link_to 'Back', pages_myaccount_path %></li>
	<% end %>
</div>

</body>
</html>