config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'

  get 'pages/about'

  controller :sessions do
	get 'login' => :new
	post 'login' => :create
	get 'logout' => :destroy
	delete 'logout' => :destroy
  end
  
  resources :items do
  put :purchase
  end
  
  resources :items do
  put :rate1
  end
  
  resources :items do
  put :rate2
  end
  
  resources :items do
  put :rate3
  end
  
  resources :items do
  put :rate4
  end
  
  resources :items do
  put :rate5
  end

  
  get 'pages/signedUp'
  
  get 'pages/myaccount'
  
  get 'pages/myitems'
  
  get 'pages/mypurchases'
  
  get 'pages/solditems'
  
  get 'search',	:to=>'items#search'
  
  get 'purchase', :to=>'items#purchase'
  
  get 'rate1', :to=>'ratings#rate1'
  
  get 'rate2', :to=>'ratings#rate2'
  
  get 'rate3', :to=>'ratings#rate3'
  
  get 'rate4', :to=>'ratings#rate4'
  
  get 'rate5', :to=>'ratings#rate5'

  resources :users
  resources :ratings
  resources :categories
  resources :items

   root 'pages#home'

end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :items, dependent: :destroy
	
	validates :name, presence: true #Not null	
	validates :name, uniqueness: true #Unique
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authorise, only: [:new, :create, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/_search.html.erb
<%= form_tag(search_path, method: :get) do %>
<%= text_field_tag(:query, params[:query]) %>
<%= submit_tag "Search for items" %>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2>Categories</h2>
  <p>Click 'Show' to bring up a list of all the items in that category:</p>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
     <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
		<% if admin? %>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
<% if admin? %> 
<%= link_to 'New Category', new_category_path %>
<% end %>
</div>

</body>
</html>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h3><%= @category.name %></h3></br>
  	There's <%= pluralize(@category.items.size, 'item') %>
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
		<th>Image</th>
		<th>Price</th>
		<th>Location</th>
		<th>Time Left</th>
		<th></th>
      </tr>
    </thead>
    <tbody>

     <% @category.items.each do |anything| %>
		 <% if anything.sold == false %>
      <tr>
        <td><%= anything.title  %></td>
        <td><%= image_tag(anything.attachment, :size => "100x50") %></td>
        <td><%= euro(anything.price) %></td>
        <td><%= anything.location %></td>
		<td><%= (30 - (Time.now - anything.created_at) / 24.hours).to_i %> Days</td>
		<td><%= link_to 'Purchase', item_purchase_path(anything.id), method: :put %></td>
		<% end %>
      </tr>

    <% end %>
    </tbody>
  </table>
  
<%= link_to 'Back', categories_path %>
</div>

</body>
</html>