config/routes.rb
Rails.application.routes.draw do

  get 'pages/home'

  get 'pages/about'

  controller :sessions do
	get 'login' => :new
	post 'login' => :create
	get 'logout' => :destroy
	delete 'logout' => :destroy
  end
  
  resources :items do
  put :purchase
  end
  
  resources :items do
  put :rate1
  end
  
  resources :items do
  put :rate2
  end
  
  resources :items do
  put :rate3
  end
  
  resources :items do
  put :rate4
  end
  
  resources :items do
  put :rate5
  end

  
  get 'pages/signedUp'
  
  get 'pages/myaccount'
  
  get 'pages/myitems'
  
  get 'pages/mypurchases'
  
  get 'pages/solditems'
  
  get 'search',	:to=>'items#search'
  
  get 'purchase', :to=>'items#purchase'
  
  get 'rate1', :to=>'ratings#rate1'
  
  get 'rate2', :to=>'ratings#rate2'
  
  get 'rate3', :to=>'ratings#rate3'
  
  get 'rate4', :to=>'ratings#rate4'
  
  get 'rate5', :to=>'ratings#rate5'

  resources :users
  resources :ratings
  resources :categories
  resources :items

   root 'pages#home'

end

app/views/layouts/_search.html.erb
<%= form_tag(search_path, method: :get) do %>
<%= text_field_tag(:query, params[:query]) %>
<%= submit_tag "Search for items" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<p id="notice"><%= notice %></p>
<html>
<head>
  <title>Auction House</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="banner">
	<div class="page-header">
		<h1>Auction House</h1>
	</div>
</div>

 <nav class="navbar navbar-default">
  <div class="container-fluid">

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
		<li><%=link_to "Home", root_path%></li>
		<li><%=link_to "Categories", categories_path%></li>
        <li><%=link_to "List an item", new_item_path%></li>
		<li><%=link_to "My Account", pages_myaccount_path%></li>
		<li><%= render 'search' %></li>

      </ul>
      <form class="navbar-form navbar-left">
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><%=mail_to "dionho43@hotmail.com", 'Contact Us'%></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" >Account </a>
          <ul class="dropdown-menu">
		  <% if !signed_in? %>
			<li role="separator" class="divider"></li>
			<li><%=link_to "Register", new_user_path %></li>
			<li role="separator" class="divider"></li>
			<li><%=link_to "Sign In", login_path %></li>
			
		<% else %>
			<li>     Welcome <%= @current_user.username %></li>
			<li role="separator" class="divider"></li>
			<li><%= link_to "Sign Out", logout_path %></li>
			<li role="separator" class="divider"></li>
            <li><%=link_to "Edit Account", edit_user_path(@current_user)%></li>
		<%end%>
            
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
 
		
		
<%= yield %>

</body>
</html>

app/views/layouts/bootstrapApp.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <h1>Hello, world!</h1>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>